### ISSUE TITLE
FaceReconstruction, can't extract face info from the video

### ISSUE THREAD

**Issue by KangZW-2001** [radekd91/inferno#19]
Have anyone meet this problem ? that's the exception:
`Processing dataset
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.38it/s]
  0%|                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]Unpacking video to '/disk/kzw/Dataset/RAVDESS/emica_rec_test/ouptu/processed_2024_Jan_02_07-46-06/01-02-02-01-01-02-01/videos'
  0%|                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo/demo_face_rec_on_video.py", line 177, in <module>
    main()
  File "demo/demo_face_rec_on_video.py", line 172, in main
    reconstruct_video(args)
  File "demo/demo_face_rec_on_video.py", line 63, in reconstruct_video
    dm.prepare_data()
  File "/home/kzw/anaconda3/envs/emica/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "/disk/kzw/infeno_nn/inferno/datasets/FaceVideoDataModule.py", line 3781, in prepare_data
    self._unpack_videos() 
  File "/disk/kzw/infeno_nn/inferno/datasets/FaceVideoDataModule.py", line 172, in _unpack_videos
    self._unpack_video(vi)
  File "/disk/kzw/infeno_nn/inferno/datasets/FaceVideoDataModule.py", line 206, in _unpack_video
    raise Exception('ffprobe', out, err)
Exception: ('ffprobe', b'', b'ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers\n  built with gcc 7.3.0 (crosstool-NG 1.23.0.449-a04d0)\n  configuration: --prefix=/tmp/build/80754af9/ffmpeg_1587154242452/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho --cc=/tmp/build/80754af9/ffmpeg_1587154242452/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc --disable-doc --enable-avresample --enable-gmp --enable-hardcoded-tables --enable-libfreetype --enable-libvpx --enable-pthreads --enable-libopus --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame --disable-nonfree --enable-gpl --enable-gnutls --disable-openssl --enable-libopenh264 --enable-libx264\n  libavutil      56. 31.100 / 56. 31.100\n  libavcodec     58. 54.100 / 58. 54.100\n  libavformat    58. 29.100 / 58. 29.100\n  libavdevice    58.  8.100 / 58.  8.100\n  libavfilter     7. 57.100 /  7. 57.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  5.100 /  5.  5.100\n  libswresample   3.  5.100 /  3.  5.100\n  libpostproc    55.  5.100 / 55.  5.100\nUnrecognized option \'r 1 -i /disk/kzw/Dataset/RAVDESS/emica_rec_test/test/video/01-02-02-01-01-02-01.mp4 -r 1  "/disk/kzw/Dataset/RAVDESS/emica_rec_test/ouptu/processed_2024_Jan_02_07-46-06/01-02-02-01-01-02-01/videos/%06d.png"\'.\nError splitting the argument list: Option not found\n')`
Last night the reconstruction worked well, but I don't know what happed. I don't think I changed anything else except the input video and output folder. I think that happens because it can't detect the face in the video and get the face frame. But I don't know how to handle it. Can anyone help? Thanks a lot

**Comment by Daydreamer-f** [comment]
Hi, I met exactly the same error as you did. How did you solve it?

**Comment by Daydreamer-f** [comment]
Hi @KangZW-2001 , I met exactly the same error as you did. How did you solve it?

**Comment by CHDTevior** [comment]
set your environment var in shell : unset LD_LIBRARY_PATH
