### ISSUE TITLE
Missing file for EMOTE

### ISSUE THREAD

**Issue by hdjang** [radekd91/inferno#24]
Hi, 
Thanks for sharing your great efforts!

I have a simple question regarding preprocessing custom data for training EMOTE 

Q) I followed preprocessing steps of EMOTE. And for "recognize_emotions" step, below line gives import error and I found that "inferno_apps.EmotionRecognition.utils.io.py" is missing in repository. How can I fix this?

from inferno_apps.EmotionRecognition.utils.io import load_model 
(inferno/inferno/models/temporal/Preprocessors.py", line 520)

Best regards
HD Jang

**Comment by Parikshat1998** [comment]
Hey, I am also trying to retrain emote, I got stuck at the segmentation step, were you able to get that right?

**Comment by radekd91** [comment]
> Hey, I am also trying to retrain emote, I got stuck at the segmentation step, were you able to get that right?

You should not need the segmentation unless you plan on training your own reconstruction network. You can skip it.

**Comment by radekd91** [comment]
> Hi, Thanks for sharing your great efforts!
> 
> I have a simple question regarding preprocessing custom data for training EMOTE
> 
> Q) I followed preprocessing steps of EMOTE. And for "recognize_emotions" step, below line gives import error and I found that "inferno_apps.EmotionRecognition.utils.io.py" is missing in repository. How can I fix this?
> 
> from inferno_apps.EmotionRecognition.utils.io import load_model (inferno/inferno/models/temporal/Preprocessors.py", line 520)
> 
> Best regards HD Jang

Thank you! The file somehow never made it from my larger private version of my codebase into the public master. I added it.
