### ISSUE TITLE
Questions about MICA preprocessing

### ISSUE THREAD

**Issue by stas-polukeev** [radekd91/inferno#33]
Hi, thanks for the great work!
I've been testing EMICA for face reconstruction and I'm mostly interested in inference. While running demo on images i see warning about MICA preprocessing of the input images being very inefficient.
I could not find anything about preprocessing in MICA, however, I might have overlooked somehting.
Could you please explain, maybe in the most general terms, what are the main steps on this preprocessing? As far as I understand it it should just have a feed forward net

**Comment by radekd91** [comment]
The MICA encoder is essentially an ArcFace (the original released network). The network expects images processed in a particular way. It warps images based on certain facial keypoints. At inference time in the forward pass I just use the original associated utility, which is not pytorch-based and hence not vectorized or running on a GPU. If you're interested in processing large amounts of data, I would recommend following the example of the stage-based data processing described in: 
https://github.com/radekd91/inferno/tree/master/inferno_apps/TalkingHead/data_processing 
In there the MICA image processing is done in the data loader processes and more efficiently.

**Comment by stas-polukeev** [comment]
Thanks for  the detailed answer!
